
# yazi.toml

[manager]
ratio = [0, 4, 0]

[opener]
# yazelix v4
edit = [
  # { run = '~/.config/yazelix/yazi/open_file.sh "$1"', desc = "Open File in a new pane" },
  { run = 'nu ~/.config/yazi/open_file.nu "$1"', desc = "Open File in a new pane" },
]

# yazelix v3
# edit = [{ exec = 'zellij edit "$1"', desc = "Open File in a new pane" }]
