[manager]
ratio = [0, 1, 0]
sort_dir_first = true
linemode = 'mtime'
show_hidden = true 


[opener]
edit = [
	{ run = 'attach_file_helix "$@"', orphan = true, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]
