matches:
  - trigger: "%ml"
    replace: me@anudeep.pro

  - trigger: "%fn"
    replace: () => { }

  - trigger: "%gP"
    replace: "git push --set-upstream origin "

  - trigger: "%gU"
    replace: "git push origin main"

  - trigger: "%gp"
    replace: "git pull --rebase origin "

  - trigger: "%gf"
    replace: "git fetch origin; git pull --rebase origin "

  - trigger: "%gc"
    replace: git commit -m "

  - trigger: "%dP"
    replace: "db push --set-upstream origin "

  - trigger: "%dU"
    replace: "db push origin main"

  - trigger: "%dp"
    replace: "db pull --rebase origin "

  - trigger: "%df"
    replace: "db fetch origin; git pull --rebase origin "

  - trigger: "%dc"
    replace: db commit -m " 

  
  - trigger: "%ll"
    replace: "{{mytime}} — #log"
    vars:
      - name: mytime
        type: date
        params:
          format: "%d-%B-%Y"
          offset: 0
          locale: en_IN

  - trigger: "%tt"
    replace: "{{mytime}} —> "
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"
          offset: 0
          locale: en_IN

  - trigger: "%ws"
    replace: "curl wttr.in"

  - trigger: "%ip"
    replace: "curl ifconfig.me"

  - trigger: "%dj"
    replace: "curl -H \"Accept: text/plain\" https://icanhazdadjoke.com; echo"

  - trigger: "%hl"
    replace: "atuin login -u achandrapaul"

